### ISSUE TITLE
Question: Is there any way to update constraints?

### ISSUE THREAD

**Issue by o-nnerb** [el-hoshino/NotAutoLayout#139]
I'm pretty close to starting using this library to remove AutoLayout dependency, but I need to be sure if some features exist.

-  Is there any method like "setOrUpdate" to set layout or update if the setting already exists?
- Can I add layout in steps? Like I want to add top layout rule and in the future time, I want to add bottom layout rule, is it possible? 
- If the subview uses AutoLayout constraint, will this library keep working?

**Comment by el-hoshino** [comment]
Hi @brennobemoura 

Sorry for late response

Actually as I mentioned in the README file, this framework has been deprecated so I personally don't recommend using it anymore if you haven't started using it yet. The only reason I'm still maintaining it is just because in the company I'm working at there're some projects still using it, so before they all transferred to other frameworks or libraries I have to make sure this framework can work well for them at least.

Answers to the questions:

> Is there any method like "setOrUpdate" to set layout or update if the setting already exists?

NotAutoLayout doesn't work like Auto Layout-based libraries. `UIViews` don't store any information related to layout (because you can't store additional information to an exist class without using Objective-C black magic), so actually a view doesn't know if it already have any layout settings.

There is a class though in NotAutoLayout that contains layout info, it's `LayoutInfoStoredView`. It's nothing special but just a subclass of `UIView` that conforms to `LayoutInfoStorable` protocol. Obviously you can't use it with class other than `UIView`, like `UITableViewCell` for instance, but if you like you can subclass that view and conform it to `LayoutInfoStorable`, just like `LayoutInfoStoredView`. After that, you can store subviews' layout info into it, and call `self.nal.layoutSubviews()` to update the view. Normally I'd recommend to just override `layoutSubviews()` method and call `nal.layoutSubviews()` inside it, so all layout stuff can be done within a layout cycle correctly.

For further information you can check the implementation of [`LayoutInfoStoredView`](https://github.com/el-hoshino/NotAutoLayout/blob/master/Sources/NotAutoLayout/LayoutInfoStorable/LayoutInfoStoredView.swift) and [`LayoutInfoStorable`](https://github.com/el-hoshino/NotAutoLayout/blob/master/Sources/NotAutoLayout/LayoutInfoStorable/LayoutInfoStorable.swift)

> Can I add layout in steps? Like I want to add top layout rule and in the future time, I want to add bottom layout rule, is it possible?

Yes TECHNICALLY you can but I won't recommend it because it's not very convenient and you may need to write tons of extensions, depending on how many kind of partial steps you'd like to make.

From parent view you can call [`parentView.nal.makeLayout(making:)`](https://github.com/el-hoshino/NotAutoLayout/blob/e66916d048d75b5f56aa3ea407e833a4e9d59dad/Sources/NotAutoLayout/LayoutControl/LayoutControlling.swift#L64), and the `making` parameter is a closure from `IndividualProperty.Initial` to `IndividualProperty.Layout`, and the result layout will be the return value of `makeLayout`. So if you'd like to you can add your own `makeLayout` method just like this but with different input or/and output type to `making` closure. For instance, I can do things like this:

```swift
func makeLayout(_ making: (LayoutMaker<IndividualProperty.Initial>) -> LayoutMaker<IndividualProperty.LeftRightTop>) -> IndividualProperty.LeftRightTop {
	
	let maker = LayoutMaker(parentView: self.body, didSetProperty: IndividualProperty.Initial())
	let layout = making(maker).didSetProperty
	
	return layout
		
}

func makeLayout(from exist: IndividualProperty.LeftRightTop, _ making: (LayoutMaker<IndividualProperty.LeftRightTop>) -> LayoutMaker<IndividualProperty.Layout>) -> IndividualProperty.Layout {
	
	let maker = LayoutMaker(parentView: self.body, didSetProperty: exist)
	let layout = making(maker).didSetProperty
	
	return layout
		
}

let partiallySetLayout = parentView.nal.makeLayout({ $0
    .setLeft(/**/)
    .setRight(/**/)
    .setTop(/**/)
})

let finalLayout = parentView.nal.makeLayout(from: partiallySetLayout, { $0
    .setBottom(/**/)
})
```

> If the subview uses AutoLayout constraint, will this library keep working?

I haven't tested that kind of situation but I theoretically there may be some effects depending on the constraints you set in your subviews.

To understand this we have to know how Auto Layout works. A typical Auto Layout cycles begins with the very child view and calculates the constraints back to the very parent (root) view, so layout rendering won't take place until all constraints calculated. Since the calculation order is bottom up (from child view to parent view), you'll find that a child view's constraints may affect its parent view. For instance if a child view has a height constraint, and the parent view has top and bottom constraint with that child view, then obviously the child's height will directly affect the parent's height.

But NotAutoLayout, or a normal layout rendering order is top down (from parent view to child view), A parent view may ask its child for its size info but theoretically the parent is just ask the child how much size it would like (via `sizeThatFits(_:)` method), the decision of child's size is directly made by parent, not child.

So in this scenario, unfortunately it IS possible that a child with Auto Layout constraints can't work well with NotAutoLayout.

But on the other hand, since we already understood how both layout systems work, we can now theoretically avoid that kind of situation by avoid self-sizing constraints in child views.

**Comment by o-nnerb** [comment]
Thanks!

I did some tests with NotAutoLayout and it worked very well. As you said, to set constraints by step, I did have to implement some methods with extension. But I didn't like the time that the library takes to resolve constraints. 

I placed in screen 5000 UIView and auto-layout resolved when I rotate the screen super fast. But with NotAutoLayout, the processor was at 100% for some seconds. In contrast, the memory was at 25 MB and AutoLayout was using 700 MB.

So, how this library is deprecated, I won't continue testing. Thanks for this repo, it's awesome 👏👏
